### ISSUE TITLE
Any reason as to why the player doesn't format the subtitles' <i> tags?

### ISSUE THREAD

**Issue by streamamos** [hoangvu12/netplayer#2]
I realised that the NetPlayer doesn't format srt or vtt in the player. The < i > tags, etc, appear as text instead of formatting the text inside.
Here's an example:

![sub](https://github.com/hoangvu12/netplayer/assets/134351107/1c5c7ad2-a6b9-4c2c-b51f-1d3e14bfd38a)

**Comment by hoangvu12** [comment]
That's because netplayer rendering it as text, to fix it, simply just render it as HTML.

**Comment by hoangvu12** [comment]
Fixed at 710acca, please try v1.16.3

**Comment by streamamos** [comment]
Thank you for the quick response and fix 😀
